### PR TITLE
Include Images from EPGdata

### PR DESCRIPTION
**Pull request by fat-fred**
EPGdata has some fanart, but they were not in the xml file

### CODE REVIEW

**Comment by yunosh** [comment]
EPGdata provides images as URLs, while XMLTV uses file locations, so this mapping won't do anything, resp. provide incorrect values.

**Comment by fat-fred** [comment]
I use this since one year now. 
The Images are shown in tvheadend and in Kodi. 

Yes. This only mappe an url. But tvh loads the Images.

**Comment by yunosh** [comment]
Good to know. Maybe the XMLTV documentation needs to be updated then too.

**Comment by knowledgejunkie** [comment]
> Good to know. Maybe the XMLTV documentation needs to be updated then too.

The current version of the XMLTV DTD specifies that the "src" attribute of an icon element should be a URI.

Where do you read that XMLTV uses file locations for icons? I totally agree that the documentation must match the DTD.

**Comment by yunosh** [comment]
Nevermind, it was exactly the opposite. EPGdata provided images with the downloaded ZIP files, while XMLTV required URIs. So if EPGdata now includes URIs, than *this* is what changed :)

**Comment by fat-fred** [comment]
Her is my next pull request.
I found this the last days.

**Comment by knowledgejunkie** [comment]
Thank you for your contribution to XMLTV :)

**Pull request merged**
