### PR TITLE
Fix #208: broken tv_grab_pt_meo

### LINKED ISSUE #208: tv_grab_pt_meo broken
XMLTV Version?
--------------
v1.0.0-1 (Debian 11 repository)

XMLTV Component?
----------------
tv_grab_pt_meo

Perl Version
------------
v5.32.1

Operating System
----------------
Linux Debian 11

What happened?
--------------
```
root@tvheadendvm:~# sudo -u hts tv_grab_pt_meo --list-channels
using config filename /home/hts/.xmltv/tv_grab_pt_meo.conf
getting list of channels: malformed JSON string, neither tag, array, object, number, string or atom, at character offset 2 (before "<!DOCTYPE html PUBLI...") at /usr/share/perl5/XMLTV/Get_nice.pm line 222.
```

What did you expect to happen?
------------------------------
output to stdout of a xml list of channels

Did you see any warnings/errors?
--------------------------------
`getting list of channels: malformed JSON string, neither tag, array, object, number, string or atom, at character offset 2 (before "<!DOCTYPE html PUBLI...") at /usr/share/perl5/XMLTV/Get_nice.pm line 222.`

What steps are needed to reproduce this issue?
----------------------------------------------
1. `root@tvheadendvm:~# sudo -u hts tv_grab_pt_meo --list-channels`

Please attach your config file below:
-------------------------------------
format=label
channel!DW_TV.meo.pt        		#   -1 : DEUTSCHE WELLE
channel!RTP1.meo.pt         		#    1 : RTP 1
channel!GLOB.meo.pt         		#   10 : GLOBO
channel!RTPM.meo.pt         		#  100 : RTP MEMÃRIA
channel!QHD.meo.pt          		#  101 : Q HD
channel!SICR.meo.pt         		#  105 : SIC RADICAL
channel!MTVPHD.meo.pt       		#  106 : MTV Portugal HD
channel!AMCBRE.meo.pt       		#  107 : AMC Break
channel!FUELTV.meo.pt       		#  108 : FUEL TV
channel!GAMET.meo.pt        		#  109 : GAMETOON
channel!C11.meo.pt          		#   11 : Canal 11
channel!ADVNCE.meo.pt       		#  110 : ADVNCE
channel!AMCCRI.meo.pt       		#  114 : AMC Crime
channel!ID.meo.pt           		#  115 : Investigation Discovery
channel!TLC.meo.pt          		#  118 : TLC
channel!GALERIA.meo.pt      		#  119 : GALERIA
channel!TVIFIC.meo.pt       		#   12 : TVI FICÃÃO
channel!SICC.meo.pt         		#  120 : SIC CARAS
channel!E_HD.meo.pt         		#  121 : E! ENTERTAINMENT HD
channel!CASACOZ.meo.pt      		#  122 : Casa e Cozinha
channel!24KTHD.meo.pt       		#  123 : 24 KITCHEN
channel!TRAXP.meo.pt        		#  124 : Travelxp
channel!FTVHD.meo.pt        		#  126 : FTV HD
channel!HGTV.meo.pt         		#  127 : Home & Garden TV
channel!MCHIC.meo.pt        		#  128 : MÃS CHIC
channel!SMAISHD.meo.pt      		#  129 : S+
channel!ABOLA.meo.pt        		#   13 : A BOLA TV
channel!MTV00S.meo.pt       		#  130 : MTV 00s
channel!MTVLIVE.meo.pt      		#  131 : MTV LIVE HD
channel!TRAHD.meo.pt        		#  132 : TRACE URBAN HD
channel!MCMP.meo.pt         		#  133 : MCM POP
channel!MCMTHD.meo.pt       		#  134 : MCM TOP HD
channel!CLUBHD.meo.pt       		#  135 : CLUBBING TV HD
channel!AFRO.meo.pt         		#  136 : AFRO MUSIC
channel!TRACETC.meo.pt      		#  137 : TRACE TOCA HD
channel!TRACEBR.meo.pt      		#  138 : Trace Brazuca
channel!ALMALUS.meo.pt      		#  139 : ALMA LUSA
channel!SPTVHD.meo.pt       		#   14 : SPORT TV +
channel!MEZZO.meo.pt        		#  140 : MEZZO
channel!MEZHD.meo.pt        		#  141 : MEZZO Live HD
channel!BOMSOM.meo.pt       		#  142 : BOMSOM TV
channel!CLASSIC.meo.pt      		#  148 : Stingray Classica
channel!DJAZZ.meo.pt        		#  149 : Stingray Djazz
channel!PORTO.meo.pt        		#   15 : PORTO CANAL
channel!ICOHD.meo.pt        		#  151 : STINGRAY ICONCERTS HD
channel!LOUD.meo.pt         		#  152 : STINGRAY LOUD HD
channel!RETRO.meo.pt        		#  153 : STINGRAY RETRO HD
channel!RTPACR.meo.pt       		#  160 : RTP AÃORES HD
channel!RTPMA.meo.pt        		#  161 : RTP MADEIRA
channel!ARTV.meo.pt         		#  162 : ARTV
channel!LVTVHD.meo.pt       		#  163 : LOCALVISÃO TV HD
channel!AZORES.meo.pt       		#  167 : AZORES TV
channel!TOROTVHD.meo.pt     		#  170 : TOROS HD
channel!CACAPHD.meo.pt      		#  172 : CAÃA E PESCA HD
channel!CACAVHD.meo.pt      		#  173 : CAÃAVISION HD
channel!C180.meo.pt         		#  180 : CANAL 180
channel!KURIAKO.meo.pt      		#  181 : Kuriakos TV HD
channel!CNOVA.meo.pt        		#  182 : CANÃÃO NOVA HD
channel!TVVERHD.meo.pt      		#  183 : TV Verdade
channel!UME.meo.pt          		#  184 : UM Europa
channel!UNIFE.meo.pt        		#  185 : UnifÃ© TV
channel!DOGTVHD.meo.pt      		#  186 : DOGTV HD
channel!PFC.meo.pt          		#  189 : PFC
channel!GNEWS.meo.pt        		#  190 : GLOBO NEWS
channel!RECHD.meo.pt        		#  191 : RECORD TV HD
channel!RECNEW.meo.pt       		#  192 : RECORD NEWS
channel!EURN.meo.pt         		#  195 : EURONEWS
channel!RTPA.meo.pt         		#  196 : RTP ÃFRICA
channel!TVA.meo.pt          		#  197 : TelevisÃ£o Ãfrica
channel!TPA.meo.pt          		#  199 : TPA INTERNACIONAL
channel!RTP2.meo.pt         		#    2 : RTP 2
channel!TCV.meo.pt          		#  202 : TCV INTERNACIONAL
channel!CNN.meo.pt          		#  205 : CNN
channel!BLOOM.meo.pt        		#  206 : BLOOMBERG
channel!CNBC.meo.pt         		#  209 : CNBC
channel!SPT1HD.meo.pt       		#   21 : SPORT.TV1
channel!SKYN.meo.pt         		#  211 : SKY NEWS
channel!BBCE.meo.pt         		#  214 : BBC ENTERTAINMENT
channel=FR24I.meo.pt        		#  216 : FRANCE 24 (I)
channel!I24I.meo.pt         		#  217 : i24 NEWS (I)
channel!NHKHD.meo.pt        		#  219 : NHK WORLD JAPAN HD
channel!SPT2HD.meo.pt       		#   22 : SPORT.TV2
channel!CGTNHD.meo.pt       		#  220 : CGTN HD
channel!CGTNDHD.meo.pt      		#  221 : CGTN-Documentary
channel!ARIRANG.meo.pt      		#  222 : ARIRANG TV
channel!EURNIHD.meo.pt      		#  223 : EURONEWS (I) HD
channel!DWTVHD.meo.pt       		#  224 : DEUTSCHE WELLE HD
channel!ALJAZHD.meo.pt      		#  225 : AL JAZEERA ENGLISH HD
channel!TRTWHD.meo.pt       		#  226 : TRT World
channel!1RUSS.meo.pt        		#  228 : CHANNEL 1 RUSSIA
channel!SPT3HD.meo.pt       		#   23 : SPORT.TV3
channel!TVEIHD.meo.pt       		#  234 : TVEi
channel!TVE24HD.meo.pt      		#  235 : TVE24
channel!TVGAL.meo.pt        		#  236 : TV GALÃCIA
channel=TELESUR.meo.pt      		#  239 : TELESUR
channel!SPT4HD.meo.pt       		#   24 : SPORT.TV4
channel=CUBAV.meo.pt        		#  240 : CUBAVISION
channel!SPT5HD.meo.pt       		#   25 : SPORT.TV5
channel!TV5HD.meo.pt        		#  250 : TV5MONDE HD
channel!BFM.meo.pt          		#  251 : BFM TV
channel!BFMB.meo.pt         		#  253 : BFM Business
channel!I24F.meo.pt         		#  254 : i24 NEWS (F)
channel!FR24F.meo.pt        		#  255 : FRANCE 24 (F)
channel!FR2HD.meo.pt        		#  256 : FRANCE 2
channel!FR3HD.meo.pt        		#  257 : FRANCE 3
channel!FR5HD.meo.pt        		#  258 : FRANCE 5
channel=ARTEHD.meo.pt       		#  259 : ARTE
channel!SPT6HD.meo.pt       		#   26 : SPORT.TV6
channel!DWTVA.meo.pt        		#  261 : DEUTSCHE WELLE (A)
channel!EURNA.meo.pt        		#  262 : EURONEWS (A)
channel!ARD.meo.pt          		#  263 : ARD
channel!ZDF.meo.pt          		#  264 : ZDF
channel!ZDFNEO.meo.pt       		#  265 : ZDFNEO
channel!3SAT.meo.pt         		#  266 : 3SAT
channel!KIKA.meo.pt         		#  267 : KIKA
channel!NBATVHD.meo.pt      		#   27 : NBA TV 
channel=BVN.meo.pt          		#  270 : BVN
channel!PROTV.meo.pt        		#  272 : PRO TV INTERNACIONAL
channel=BNT4.meo.pt         		#  273 : BNT 4
channel!KBS.meo.pt          		#  277 : KBS WORLD
channel!CCTV4HD.meo.pt      		#  278 : CCTV 4 HD
channel=PHCNE.meo.pt        		#  279 : PHOENIX CNE
channel!FIGHTSP.meo.pt      		#   28 : FIGHT SPORTS
channel=NICKUKR.meo.pt      		#  280 : Nickelodeon Ukraine Pluto TV
channel!FREEDOM.meo.pt      		#  281 : Freedom
channel!UKR1.meo.pt         		#  282 : Ukraine 1
channel!UKR2.meo.pt         		#  283 : Ukraine 2
channel!NLOTV2.meo.pt       		#  284 : NLO TV2
channel!STARCIN.meo.pt      		#  285 : Star Cinema
channel!STARFAM.meo.pt      		#  286 : Star Family
channel!XSPORT.meo.pt       		#  287 : X Sport
channel!RYBALKA.meo.pt      		#  288 : Rybalka TV
channel!ITALIA.meo.pt       		#  289 : RAI Italia
channel!RAI1.meo.pt         		#  290 : RAI 1
channel!RAI2.meo.pt         		#  291 : RAI 2
channel!RAI3.meo.pt         		#  292 : RAI 3
channel!RAINEWS.meo.pt      		#  293 : RAI News
channel!SCUOLA.meo.pt       		#  294 : RAI Scuola
channel!STORIA.meo.pt       		#  295 : RAI Storia
channel!ZEETV.meo.pt        		#  296 : ZEE TV
channel!ZEECIN.meo.pt       		#  297 : ZEE CINEMA
channel!SETAS.meo.pt        		#  298 : SET ASIA
channel!MAX.meo.pt          		#  299 : SET MAX
channel!SIC.meo.pt          		#    3 : SIC
channel!SLBHD.meo.pt        		#   30 : BTV 
channel!ELEVEN1.meo.pt      		#   31 : ELEVEN 1
channel!ELEVEN2.meo.pt      		#   32 : ELEVEN 2 
channel!ELEVEN3.meo.pt      		#   33 : ELEVEN 3 
channel!ELEVEN4.meo.pt      		#   34 : ELEVEN 4 
channel!ELEVEN5.meo.pt      		#   35 : ELEVEN 5 
channel!PBTVHD.meo.pt       		#  350 : PLAYBOY TV HD
channel!VENUS.meo.pt        		#  351 : VENUS
channel!SEXTRM.meo.pt       		#  352 : SEXTREME
channel!PENTHG.meo.pt       		#  353 : PENTHOUSE GOLD
channel!BODYSEX.meo.pt      		#  354 : BODY SEX
channel!HOTHD.meo.pt        		#  355 : HOT HD
channel!HOTTAB.meo.pt       		#  356 : HOT TABOO
channel!HOTMAN.meo.pt       		#  357 : HOT MAN
channel!VIVID.meo.pt        		#  358 : VIVID RED
channel!ELEVEN6.meo.pt      		#   36 : ELEVEN 6 
channel!PLAY.meo.pt         		#  361 : PLAYBOY TV
channel!HOT.meo.pt          		#  362 : HOT
channel!SCPHD.meo.pt        		#   37 : SPORTING TV HD
channel!EURHD.meo.pt        		#   38 : EUROSPORT 1 HD
channel!EURS2HD.meo.pt      		#   39 : EUROSPORT 2 HD
channel!TVI.meo.pt          		#    4 : TVI
channel!DISNY.meo.pt        		#   40 : DISNEY CHANNEL
channel!TRAXP4K.meo.pt      		#  400 : Travelxp 4K HDR
channel!MCSUHD.meo.pt       		#  401 : MCS TV ULTRA HD
channel!CART.meo.pt         		#   41 : CARTOON NETWORK
channel!BIGGS.meo.pt        		#   42 : BIGGS
channel!SICK.meo.pt         		#   43 : SIC K
channel!NICKELO.meo.pt      		#   44 : NICKELODEON
channel!DISNYJ.meo.pt       		#   45 : Disney Junior
channel!PANDA.meo.pt        		#   46 : PANDA HD
channel!BOOM.meo.pt         		#   47 : Boomerang
channel!BABYT.meo.pt        		#   49 : BABY TV
channel!SICN.meo.pt         		#    5 : SIC NOTICIAS
channel!LOLLY.meo.pt        		#   50 : Lolly kids
channel!RTP1SD.meo.pt       		#  501 : RTP 1
channel!RTP2SD.meo.pt       		#  502 : RTP 2
channel!SICSD.meo.pt        		#  503 : SIC
channel!TVISD.meo.pt        		#  504 : TVI
channel!SICNSD.meo.pt       		#  505 : SIC NOTÃCIAS
channel!RTP3SD.meo.pt       		#  506 : RTP 3
channel!CNNPTSD.meo.pt      		#  507 : CNN Portugal
channel!CMTVSD.meo.pt       		#  508 : CMTV
channel!SICMSD.meo.pt       		#  509 : SIC MULHER
channel!PANDAK.meo.pt       		#   51 : Panda KIDS
channel!GLOBSD.meo.pt       		#  510 : GLOBO
channel!C11SD.meo.pt        		#  511 : Canal 11
channel!TVIFISD.meo.pt      		#  512 : TVI FICÃÃO
channel!ABOLASD.meo.pt      		#  513 : A BOLA TV
channel!SPTV.meo.pt         		#  514 : SPORT TV +
channel!PORTOSD.meo.pt      		#  515 : PORTO CANAL
channel!SPTV1.meo.pt        		#  521 : SPORT.TV1
channel!SPTV2.meo.pt        		#  522 : SPORT.TV2
channel!SPTV3.meo.pt        		#  523 : SPORT.TV3
channel!SPTV4.meo.pt        		#  524 : SPORT.TV4
channel!SPTV5.meo.pt        		#  525 : SPORT.TV5
channel!SPTV6.meo.pt        		#  526 : SPORT.TV6
channel!SLB.meo.pt          		#  530 : BTV
channel!ELEV1SD.meo.pt      		#  531 : ELEVEN 1
channel!ELEV2SD.meo.pt      		#  532 : ELEVEN 2
channel!ELEV3SD.meo.pt      		#  533 : ELEVEN 3
channel!ELEV4SD.meo.pt      		#  534 : ELEVEN 4
channel!ELEV5SD.meo.pt      		#  535 : ELEVEN 5
channel!ELEV6SD.meo.pt      		#  536 : ELEVEN 6
channel!SCP.meo.pt          		#  537 : SPORTING TV
channel!EURSP.meo.pt        		#  538 : EUROSPORT 1
channel!EURS2.meo.pt        		#  539 : EUROSPORT 2
channel!DISNYSD.meo.pt      		#  540 : DISNEY CHANNEL
channel!CARTSD.meo.pt       		#  541 : CARTOON NETWORK
channel!SICKSD.meo.pt       		#  543 : SIC K
channel!DISNYJS.meo.pt      		#  545 : DISNEY JUNIOR
channel!PANDASD.meo.pt      		#  546 : PANDA
channel!TVCTOPH.meo.pt      		#   55 : TVCine TOP
channel!PANDAKS.meo.pt      		#  551 : Panda KIDS
channel!TVCTOP.meo.pt       		#  555 : TVCine TOP
channel!TVCEDI.meo.pt       		#  556 : TVCINE Edition
channel!TVCEMO.meo.pt       		#  557 : TVCINE Emotion
channel!TVCACT.meo.pt       		#  558 : TVCine Action
channel!TVCEDIH.meo.pt      		#   56 : TVCINE Edition
channel!CINE.meo.pt         		#  560 : CINEMUNDO
channel!HOLLW.meo.pt        		#  561 : HOLLYWOOD 
channel!FOXM.meo.pt         		#  562 : FOX MOVIES
channel!AMC.meo.pt          		#  563 : AMC
channel!AXNM.meo.pt         		#  564 : AXN MOVIES
channel!VODSD.meo.pt        		#  569 : MEO VIDEOCLUBE
channel!TVCEMOH.meo.pt      		#   57 : TVCINE Emotion
channel!FOX.meo.pt          		#  570 : FOX
channel!FLIFE.meo.pt        		#  571 : FOX LIFE
channel!FOXCR.meo.pt        		#  572 : FOX CRIME
channel!FOXCOM.meo.pt       		#  573 : FOX COMEDY
channel!AXN.meo.pt          		#  574 : AXN
channel!AXNWH.meo.pt        		#  575 : AXN WHITE
channel!SYFY.meo.pt         		#  576 : SYFY
channel!TVCACTH.meo.pt      		#   58 : TVCine Action
channel!DEST.meo.pt         		#  589 : MEO DESTAQUES
channel!DISCV.meo.pt        		#  590 : DISCOVERY CHANNEL
channel!HIST.meo.pt         		#  591 : CANAL HISTÃRIA
channel!ODISS.meo.pt        		#  592 : ODISSEIA
channel!NGC.meo.pt          		#  595 : NATIONAL GEOGRAPHIC CHANNEL
channel!WILD.meo.pt         		#  596 : National Geographic Wild
channel=TVIRSD.meo.pt       		#  599 : TVI Reality â Big Brother
channel!RTP3.meo.pt         		#    6 : RTP 3
channel!CINEHD.meo.pt       		#   60 : CINEMUNDO HD
channel!Q.meo.pt            		#  601 : Q
channel!SICRSD.meo.pt       		#  605 : SIC RADICAL
channel!MTV.meo.pt          		#  606 : MTV Portugal
channel!HOLHD.meo.pt        		#   61 : HOLLYWOOD
channel!AMCCRIS.meo.pt      		#  614 : AMC Crime
channel!FOXMH.meo.pt        		#   62 : FOX MOVIES
channel!SICCSD.meo.pt       		#  620 : SIC CARAS
channel!E_.meo.pt           		#  621 : E! ENTERTAINMENT
channel!24KITC.meo.pt       		#  623 : 24 KITCHEN
channel!FTV.meo.pt          		#  626 : FTV
channel!MCHICSD.meo.pt      		#  628 : MÃS CHIC
channel!AMCHD.meo.pt        		#   63 : AMC HD
channel!TRACE.meo.pt        		#  632 : TRACE URBAN
channel!MCMT.meo.pt         		#  634 : MCM TOP
channel!CLUBB.meo.pt        		#  635 : CLUBBING TV
channel!AXNMHD.meo.pt       		#   64 : AXN MOVIES HD
channel!RTPACRS.meo.pt      		#  660 : RTP AÃORES
channel!LVTV.meo.pt         		#  663 : LOCALVISÃO TV
channel!TOROTV.meo.pt       		#  670 : TOROS
channel!CACAP.meo.pt        		#  672 : CAÃA E PESCA
channel!CACAV.meo.pt        		#  673 : CAÃAVISION
channel!CNOVASD.meo.pt      		#  682 : CANÃÃO NOVA
channel!UMESD.meo.pt        		#  684 : UM Europa
channel!DOGTV.meo.pt        		#  686 : DOGTV
channel!VOD.meo.pt          		#   69 : MEO VIDEOCLUBE HD
channel!GNEWSSD.meo.pt      		#  690 : GLOBO NEWS
channel!TVREC.meo.pt        		#  691 : RECORD TV
channel!CNNPT.meo.pt        		#    7 : CNN Portugal
channel!FOXHD.meo.pt        		#   70 : FOX HD
channel!CNBCSD.meo.pt       		#  709 : CNBC
channel!FLIFEH.meo.pt       		#   71 : FOX LIFE HD
channel!I24ISD.meo.pt       		#  717 : i24 NEWS (I)
channel!FOXCHD.meo.pt       		#   72 : FOX CRIME
channel=CGTN.meo.pt         		#  720 : CGTN
channel!EURNI.meo.pt        		#  723 : EURONEWS (I)
channel!ALJAZ.meo.pt        		#  725 : AL JAZEERA ENGLISH
channel!FOXCOH.meo.pt       		#   73 : FOX COMEDY
channel!TVGALSD.meo.pt      		#  736 : TV GALÃCIA
channel!AXNHD.meo.pt        		#   74 : AXN HD
channel!AXWHD.meo.pt        		#   75 : AXN WHITE HD
channel!TV5.meo.pt          		#  750 : TV5MONDE
channel!SYFHD.meo.pt        		#   76 : SYFY HD
channel!DIZI.meo.pt         		#   77 : DIZI CHANNEL
channel=CCTV4.meo.pt        		#  778 : CCTV 4
channel!PHCNESD.meo.pt      		#  779 : PHOENIX CNE
channel!ITALIAS.meo.pt      		#  789 : RAI Italia
channel!RAI1SD.meo.pt       		#  790 : RAI 1
channel!RAI2SD.meo.pt       		#  791 : RAI 2
channel!RAI3SD.meo.pt       		#  792 : RAI 3
channel!RNEWSSD.meo.pt      		#  793 : RAI News24
channel!SCUOLAS.meo.pt      		#  794 : RAI Scuola
channel!STORIAS.meo.pt      		#  795 : RAI Storia
channel!CMTV.meo.pt         		#    8 : CMTV
channel!DEST.meo.pt         		#   89 : MEO DESTAQUES HD
channel!SICM.meo.pt         		#    9 : SIC MULHER
channel!DISCVHD.meo.pt      		#   90 : DISCOVERY CHANNEL HD
channel!HISTHD.meo.pt       		#   91 : CANAL HISTÃRIA HD
channel!ODISSHD.meo.pt      		#   92 : ODISSEIA HD
channel!NGHD.meo.pt         		#   95 : NATIONAL GEOGRAPHIC CHANNEL HD
channel!WILDHD.meo.pt       		#   96 : National Geographic Wild HD
channel=TVIR.meo.pt         		#   99 : TVI Reality â Big Brother

Any other information?
----------------------
I've been using another grabber, just tried this one now.

### PR DESCRIPTION
**Pull request by jlbribeiro**
What type of Pull Request is this?
----------------------------------
- [x] fixes/improves existing functionality

Does this PR close any currently open issues?
---------------------------------------------
This PR fixes #208.

Please explain what this PR does
--------------------------------
`tv_grab_pt_meo` currently had several issues:
- the API endpoints have been moved to a different host/path;
- the JSON payloads being `POST`ed to the API were malformed (the structure remains the same), which were rejected by the "new" API;
- the API rejects requests without an `Origin` header matching `https://www.meo.pt`.

This PR addresses those issues, and extends [XMLTV::Get_nice::post_nice_json()](https://github.com/XMLTV/xmltv/blob/f84a264383266b63bcd57a5570c4079ce0535111/grab/Get_nice.pm#L195) to accept an **optional** hash of HTTP headers to be included in the HTTP request; I wasn't sure whether this would feel the right approach, but given this function [only appears to be used in `tv_grab_pt_meo`](https://github.com/search?q=repo%3AXMLTV%2Fxmltv%20post_nice_json&type=code) I thought it was ok. Any suggestions more than welcome.

Any other information?
----------------------
**I am not at all familiar with Perl**; read a couple of things to understand some of the basics, what was the meaning of the `$$` signature, ... I believe the changes "make sense", but I feel there might be some Perl-specifics I might be missing. Please advise if so.

This change **has not** been discussed on the xmltv-devel mailing list.

Where have you tested these changes?
------------------------------------
**Operating System:** Alpine Linux `v3.18.4`

**Perl Version:** `v5.36.1`

### CODE REVIEW

**Comment by moob158** [comment]
anyone can build xmltv.exe for windows?

I tried to build it, but give me errors on build

**Comment by honir** [comment]
Nice detective work! However...

Spoofing the `Origin` header -- to pretend to be the Meo app when you're not -- is not something we would support in the XMLTV project.

**Comment by jlbribeiro** [comment]
@moob158 I had written a long response but it is probably invalid now (see @honir's comment above, and mine further below); will leave some notes though.
I get "no programmes found" for `DW_TV` (which has an `id` of -1) as well, but not for other channels. Trying to grab all the channels I'm now hitting a different error related to some code that is only being exercised after this fix (`Label not found for "next PROG" at /usr/bin/tv_grab_pt_meo line 579`). The API contains many inconsistencies (channels with no `sigla`, duplicate channel IDs, ...), so it would probably require more work. But in any case, can you provide the stderr for `tv_grab_pt_meo --fast --debug`?

---

@honir I feared that :P I had understood XMLTV strives to be a "good netizen", but was _hoping_ not spoofing the `User-Agent` (and allowing services to block so if they wanted) passed that criterion. I guess that means this grabber is broken for good, if that's the case. Should it be removed, then? Seeing the comments on #208, I believe `pt_vodafone` might be a good enough replacement, as they probably share _most_ of the channel grid.
(And thank you for all your work on the XMLTV project, btw!)

**Comment by rmeden** [comment]
So adding an Origin header and keeping an XMLTV user-agent works?  That's interesting... I can see the argument "Origin" is really just part of the API and if we're setting user-agent, we're not hiding who we are (and easily block-able if desired).  Geoff, did you realize that user-agent wasn't changing?

**Comment by honir** [comment]
`Origin` is not part of the API. It is a HTTP header normally set by a browser (or app) to indicate the source of the request. Thus it performs a similar function to the `User-Agent` but at a deeper level.

By spoofing the `Origin` you are hiding who you are: pretending to be someone else. 
>`Origin => 'https://www.meo.pt'`

You are effectively saying, "trust me, I'm from the Meo app"...but you're not. You're really xmltv.org!

(This is why _browsers_ do not allow manual setting of the `Origin` header since it opens the browser up to cross-site security issues.)

As the site is actively checking the `Origin` header they are clearly expecting only requests from their own app to be permitted.

**Comment by jlbribeiro** [comment]
@rmeden Let me clarify that I agree with @honir; `Origin` is a [forbidden header name](https://developer.mozilla.org/en-US/docs/Glossary/Forbidden_header_name), i.e. cannot be modified programmatically. Browsers send it implicitly on certain contexts, and as it is not modifiable (except outside the context of a browser) it is sometimes used as a trusting mechanism. The fact the API checks its value is almost surely on purpose (although, as you can see, it is not an actual trust mechanism in any way). I'm fully aware I was discussing semantics above, I was just trying to move the "line" to include `Origin` but exclude `User-Agent` :stuck_out_tongue:

With that said, I'm assuming this PR should be closed (and that `tv_grab_pt_meo` should be removed from this project)? @honir

**Pull request closed without merging**
